### ISSUE TITLE
pypi install

### ISSUE THREAD

**Issue by gureckis** [piantado/LOTlib#33]
hi there,
is this project still supported and if so could I help by getting this on pypi so people can install it in a more usual way? (e.g., `pip install lotlib`)

**Comment by piantado** [comment]
Oh thanks! We started porting it to python3, which will be the new official version, but it's still not completed: https://github.com/piantado/LOTlib3 
I never wanted to have an official release because it still needs good documentation and tests. 

Though, mainly what happened is that we switched to developing a new library in C++ that does the same thing, but about 1000x faster: https://github.com/piantado/Fleet 
(it actually does have some documentation, but it's still in development)

**Comment by gureckis** [comment]
Cool, although lack of documentation and test  has never stopped anyone from releasing software on pypi.  ;)

**Comment by piantado** [comment]
Well actually LOTlib3 now has some documentation ported over (still not perfectly up to date) and a bunch of working examples. I've been removing/rewriting some of the complexities in LOTlib that ended up not being helpful. Please let me know if you're using LOTlib3 and I can try to fix anything you need!
